# Generated by Django 5.1.2 on 2024-11-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_title_subtask_name_rename_title_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='Default Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='Default Title', max_length=200),
        ),
    ]
